version: "3.9"
services:
    www:
        build: ./src/www
        ports: 
            - "8080:80"
        volumes:
            - ./src/www:/var/www/html/
        links:
            - db
            - chat
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: db_app_academica
            MYSQL_USER: admin
            MYSQL_PASSWORD: academicaUGB2021
            MYSQL_ROOT_PASSWORD: academicaUGB2021
        volumes:
            - ./src/mysql/dump:/docker-entrypoint-initdb.d
            - ./src/mysql:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    chat:
        build: ./src/nodejs
        depends_on:
            - mongodb
        ports:
            - "3001:3001"
        volumes:
            - ./src/nodejs/server:/opt/app
            - /opt/app/node_modules
        links:
            - mongodb
    mongodb:
        image: mongo
        expose:
            - "27017"
        volumes:
            - mongodata:/data/db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: academicaUGB2021
            MYSQL_ROOT_PASSWORD: academicaUGB2021
volumes:
    persistent:
    mongodata:
